services:
  esp32-sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esp32-sim
    restart: unless-stopped
    ports:
      - "9100:9100"
      - "8000:8000"
    volumes:
      - esp32-flash:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "32M"
    networks:
      - brteste01

volumes:
  esp32-flash:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=16m

networks:
  brteste01:
    external: true 