global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

# Aponta para o node exporter alvo para coletar as métricas.
  - job_name: 'sensores'
    static_configs:
      - targets: ['172.18.0.2:8000','172.18.0.3:8000', '172.18.0.4:8000', '172.18.0.5:8000']

# Aponta para outro node exporter alvo para coletar as métricas.
#  - job_name: 'alvo-02'
#    static_configs:
#      - targets: ['192.168.xx.xx:9100']      