version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: broker_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./config/pwfile:/mosquitto/config/pwfile
    networks:
      - brteste01

networks:
  brteste01:
    external: true