version: '3.8'

services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    user: root
    cap_add:
      - NET_ADMIN
    stdin_open: true
    volumes:
    - ./prometheus:/etc/prometheus
    tty: true
    ports:
    - 9090:9090
    restart: always    
    networks:
      - brteste02

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      GF_LOG_FILTERS: rendering:debug
#      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SERVER_HTTP_PORT: '3000'
      GF_SERVER_PROTOCOL: http
      #GF_SMTP_ENABLED: 'true'
      #GF_SMTP_HOST: smtp.gmail.com
      #GF_SMTP_USER: seu_email@gmail.com.br
      #GF_SMTP_PASSWORD: xxxxx
    user: root
    cap_add:
      - NET_ADMIN
    ports:
    - 3000:3000
    restart: unless-stopped  
    networks:
      - brteste02

networks:
  brteste02:
    external: true 
