# Stage 1: pega o Prometheus oficial
FROM prom/prometheus:latest as prometheus

# Stage 2: constrói em Alpine com ferramentas extras
FROM alpine:3.20

RUN apk add --no-cache iperf3 iputils iproute2 net-tools

# Copia binário e configs do Prometheus
COPY --from=prometheus /bin/prometheus /bin/
COPY --from=prometheus /etc/prometheus /etc/prometheus

EXPOSE 9090
VOLUME ["/prometheus"]

ENTRYPOINT ["prometheus"]
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
