version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - brteste02

  prometheus:
    image: prom/prometheus
    restart: always
    user: root ### usuário root para criar uma rota de volta para a rede 172.18.0.0/24
    container_name: "prometheus_controller"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - brteste02

  grafana:
    image: grafana/grafana-oss
    container_name: "grafana"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - brteste02

volumes:
  grafana_data:

networks:
  brteste02:
    external: true