global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mqtt_exporter'
    static_configs:
    #monitoramento das métricas enviadas e parseadas pelo container mqtt-exporter
      - targets: ['mqtt_exporter:9114']

  - job_name:       'node'

    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['172.19.0.3:8080', '172.19.0.4:8081']
        labels:
          group: 'sensores-mqtt'